name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Explain why this job ran'
        uses: octo-org/action-name@main
        with:
          entrypoint: /bin/echo
          args: The ${{ github.event_name }} event triggered this step

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Build and Test'
        run: mvn --batch-mode --no-transfer-progress -Darchetype.test.ignoreEOLStyle=true verify archetype:integration-test

      - name: 'Publish package'
        run: mvn --batch-mode -Dmaven.test.skip=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}