name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Build and Test'
        run: ./mvnw --batch-mode --no-transfer-progress -Darchetype.test.ignoreEOLStyle=true verify archetype:integration-test

      - name: 'Publish package'
        run: ./mvnw --batch-mode -Dmaven.test.skip=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}